- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - keystone-dsvm-functional
        - keystone-dsvm-functional-federation:
            voting: false
    gate:
      jobs:
        - keystone-dsvm-functional
